

#         Powered by TabooLib 5.0         #


name: ${name}
main: ${main}
version: ${version}
authors: ['无名']
softdepend: [AreaShop,QuickShop]

api-version: 1.12

lib-download: true
lib-version: ${libVersion}
loader-version: ${loaderVersion}
